In [2]:
import pandas as pd
import numpy as np

In [7]:
pd.set_option('display.max_columns', None)

In [3]:
data=pd.read_excel('../Jaehoon/fifinal_merge_data.xlsx')
data

,Unnamed: 0,경주일자,경주번호,경주거리,착순,출주번호,마필연령,마필성별,경주기록(초),부담중량,...,"(360,)","(800,)","(900,)","(1000,)","(1110,)","(1200,)","(1400,)","(1610,)","(1700,)","(1800,)"
0,0,20230624,1,800,1,1,-1.671258,-1,68.1,-0.256074,...,0,1,0,0,0,0,0,0,0,0
1,1,20230624,1,800,2,4,0.185695,1,68.5,-0.896258,...,0,1,0,0,0,0,0,0,0,0
2,2,20230624,1,800,3,9,-1.671258,0,68.5,0.384111,...,0,1,0,0,0,0,0,0,0,0
3,3,20230624,1,800,4,3,0.185695,0,68.6,1.024295,...,0,1,0,0,0,0,0,0,0,0
4,4,20230624,1,800,5,8,0.185695,0,69.0,0.384111,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28678,28678,20190111,9,900,6,8,-0.654654,1,64.1,0.098853,...,0,0,1,0,0,0,0,0,0,0
28679,28679,20190111,9,900,7,3,1.527525,1,64.2,1.746409,...,0,0,1,0,0,0,0,0,0,0
28680,28680,20190111,9,900,8,1,-0.654654,1,64.5,-0.889680,...,0,0,1,0,0,0,0,0,0,0
28681,28681,20190111,9,900,9,4,1.527525,1,64.6,-0.230658,...,0,0,1,0,0,0,0,0,0,0
28682,28682,20190111,9,900,10,6,-0.654654,1,65.1,0.098853,...,0,0,1,0,0,0,0,0,0,0

In [4]:
data=data.drop(columns=['Unnamed: 0'])
data=data.drop(columns=['제주4코너통과기록','조교사경력(년)','기수최근1년간1착승률','기수최근1년간2착승률','조교사최근1년간1착승률','조교사최근1년간2착승률','조교사위탁경주마1위승률','조교사위탁경주마2위승률'])
data=data.drop(columns=['조교사위탁경주마출전횟수','조교사최근1년간출전횟수'])
data['기수통산승률']=data['기수통산1착승률']+data['기수통산2착승률']
data['조교사통산승률']=data['조교사통산1착승률']+data['조교사통산2착승률']
data=data.drop(columns=['기수통산1착승률','기수통산2착승률','조교사통산1착승률','조교사통산2착승률'])
data=data.drop(columns=['3시간신적설(cm)'])
data=data.drop(columns=['mom_total_in3','dad_total_in3','mom_total','dad_total','dad_post','mom_post'])

In [5]:
data=data.drop(columns=['mom_rating','dad_rating'])

In [36]:
pd.set_option('display.max_columns', None)


a=data.corr()
#a['조교사1착승률'].sort_values(ascending=False)
#조교사통산출전횟수는 조교사경력(년)과 상관관계성 높음
#조교사통산1착승률은 2착승률과 상관관계성 높음
#기수통산1착승률은 2착승률과 높음 (최근 통산 둘 중 하나 선택)
#a['max_post'].sort_values(ascending=False)
data[data['레이팅']==0]['레이팅']=29

C:\Users\wjswp\AppData\Local\Temp\ipykernel_19684\978140445.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[data['레이팅']==0]['레이팅']=29

In [8]:
data

,경주일자,경주번호,경주거리,착순,출주번호,마필연령,마필성별,경주기록(초),부담중량,기수경력(년),조교사통산출전횟수,마체중,체중증감,주로상태_함수율,혈통,등급,레이팅,max_post,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),지면온도(°C),avg_temp,horse_total_post1,horse_total_post2,horse_recent_post1,horse_recent_post2,"(20,)","(50,)","(70,)","(90,)","(110,)","(140,)","(160,)","(180,)","(200,)","(230,)","(250,)","(270,)","(290,)","(320,)","(340,)","(360,)","(800,)","(900,)","(1000,)","(1110,)","(1200,)","(1400,)","(1610,)","(1700,)","(1800,)",기수통산승률,조교사통산승률
0,20230624,1,800,1,1,-1.671258,-1,68.1,-0.256074,-0.457800,0.993131,-1.283846,1.607346,4,1,0.0,0,0.527273,27.9,0.0,3,110,56,46.2,26.275,2.897647,-0.679572,2.897647,-0.679572,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1.454217,-1.859847
1,20230624,1,800,2,4,0.185695,1,68.5,-0.896258,-1.635000,0.219819,1.716714,-2.447220,4,1,0.0,0,0.534247,27.9,0.0,3,110,56,46.2,26.275,-0.446589,1.222662,-0.446589,1.222662,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,-3.364229,0.802793
2,20230624,1,800,3,9,-1.671258,0,68.5,0.384111,-1.242600,-0.684358,-0.300056,0.448898,4,1,0.0,0,0.520000,27.9,0.0,3,110,56,46.2,26.275,-0.128091,-0.679572,-0.128091,-0.679572,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,2.201113,3.971578
3,20230624,1,800,4,3,0.185695,0,68.6,1.024295,0.327000,-0.479228,1.224819,1.028122,4,1,0.0,0,0.328671,27.9,0.0,3,110,56,46.2,26.275,-0.128091,2.100616,-0.128091,2.100616,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,2.945208,1.685280
4,20230624,1,800,5,8,0.185695,0,69.0,0.384111,-0.327000,0.013031,-0.546004,0.014481,4,1,0.0,0,0.333456,27.9,0.0,3,110,56,46.2,26.275,-0.858441,0.087377,-0.858441,0.087377,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,-1.459360,-2.051057
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28678,20190111,9,900,6,8,-0.654654,1,64.1,0.098853,-1.086500,-0.407759,0.381471,0.302063,8,0,0.0,0,0.002883,7.6,0.0,2,270,64,12.0,7.875,0.253474,1.609586,0.333333,0.333333,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,-2.117246,2.480313
28679,20190111,9,900,7,3,1.527525,1,64.2,1.746409,0.072433,-0.841425,0.641565,-0.285281,8,0,0.0,0,0.002883,7.6,0.0,2,270,64,12.0,7.875,-0.691631,-1.451202,0.333333,0.333333,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,4.492650,0.481253
28680,20190111,9,900,8,1,-0.654654,1,64.5,-0.889680,1.231367,0.419693,-1.872676,-0.453094,8,0,0.0,0,0.002883,7.6,0.0,2,270,64,12.0,7.875,0.031869,0.036986,0.333333,0.333333,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,-0.582417,-0.655791
28681,20190111,9,900,9,4,1.527525,1,64.6,-0.230658,1.955700,1.289980,1.075055,0.218156,8,0,0.0,0,0.002883,7.6,0.0,2,270,64,12.0,7.875,-0.927190,-0.482149,0.333333,0.333333,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1.365729,-2.766708
28682,20190111,9,900,10,6,-0.654654,1,65.1,0.098853,-0.362167,0.135211,1.248451,-0.704813,8,0,0.0,0,0.002883,7.6,0.0,2,270,64,12.0,7.875,-0.867047,-0.837812,0.333333,0.333333,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,-0.127410,-2.352982

In [8]:
data=data.drop(columns=['경주거리'])

In [3]:
pd.set_option('display.max_rows',20)

In [24]:
unique = data[["경주일자",	"경주번호"]].drop_duplicates()
unique = unique.reset_index()
unique

      index      경주일자  경주번호
0         0  20230624     1
1        10  20230624     2
2        20  20230624     3
3        30  20230624     4
4        40  20230624     5
...     ...       ...   ...
2863  28634  20190111     5
2864  28643  20190111     6
2865  28653  20190111     7
2866  28663  20190111     8
2867  28673  20190111     9

[2868 rows x 3 columns]

In [25]:
data["key"]=0
for i in range(len(unique)):
    data.loc[(data["경주일자"]==unique["경주일자"][i])&(data["경주번호"]==unique["경주번호"][i]), "key"] = i

In [26]:
data["경주일자"]<20220701

0        False
1        False
2        False
3        False
4        False
         ...
28678     True
28679     True
28680     True
28681     True
28682     True
Name: 경주일자, Length: 28683, dtype: bool

In [186]:
data800=data[data["경주거리"]==800]
data1000=data[data["경주거리"]==1000]
data1110=data[data["경주거리"]==1110]
data1400=data[data["경주거리"]==1400]
data900=data[data["경주거리"]==900]
data1200=data[data["경주거리"]==1110]
data1700=data[data["경주거리"]==1400]
data1800=data[data["경주거리"]==900]

In [12]:
drop_data=data

In [188]:
# drop_data["3등이내"] = drop_data["착순"]
# drop_data["5등이내"] = drop_data["착순"]
# drop_data.loc[drop_data["착순"]>3,"3등이내"]=0
# drop_data.loc[drop_data["착순"]>5,"5등이내"]=0

In [27]:
from xgboost import XGBRegressor
from sklearn.metrics import accuracy_score
X_train = drop_data[data["경주일자"]<20220701].drop(["경주기록(초)", "key"], axis=1)
X_test = drop_data[data["경주일자"]>=20220701].drop(["경주기록(초)", "key"], axis=1) 
y_train = drop_data[data["경주일자"]<20220701]["경주기록(초)"]
y_test = drop_data[data["경주일자"]>=20220701]["경주기록(초)"]

params = {
    'max_depth':5,
    'reg_lambda':1,
    'learning_rate': 0.1,
    'n_estimators': 100
}
xgb_reg = XGBRegressor(params = params)
xgb_reg.fit(X_train, y_train)

# Make predictions on the test set
y_pred = xgb_reg.predict(X_test)

[00:23:03] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-08de971ced8a8cdc6-1/xgboost/xgboost-ci-windows/src/learner.cc:767:
Parameters: { "params" } are not used.

In [28]:
pred_key = pd.concat([drop_data[data["경주일자"]>=20220701]["key"], pd.DataFrame(y_pred)], axis=1)
pred_key.columns=["key",	"y_pred"]

true_key = pd.concat([drop_data[data["경주일자"]>=20220701]["key"], pd.DataFrame(y_test)], axis=1)
true_key.columns=["key",	"y_test"]

In [29]:
pred_key["in5"] = 0
for i in pred_key["key"].unique():
    index = pred_key[pred_key["key"]==i].sort_values(by="y_pred", ascending=True)[:5].index
    pred_key.loc[index,"in5"]=1

In [30]:
true_key["in3"] = 0
for i in true_key["key"].unique():
    index = true_key[true_key["key"]==i].sort_values(by="y_test", ascending=True)[:3].index
    true_key.loc[index,"in3"]=1

In [17]:
pred_key.head(10)

   key     y_pred  in5
0    0  67.047195    1
1    0  68.020203    1
2    0  68.587212    1
3    0  68.755562    1
4    0  69.248886    1
5    0  70.281517    0
6    0  70.437332    0
7    0  71.233994    0
8    0  72.264755    0
9    0  73.306717    0

In [18]:
true_key.head(10)

   key  y_test  in3
0    0    68.1    1
1    0    68.5    1
2    0    68.5    1
3    0    68.6    0
4    0    69.0    0
5    0    70.2    0
6    0    70.7    0
7    0    70.8    0
8    0    71.1    0
9    0    72.0    0

In [31]:
count = 0
for key in true_key["key"].unique():
    num = sum(true_key.loc[true_key["key"]==key,"in3"]&pred_key.loc[pred_key["key"]==key,"in5"])
    if num==3:
        count+=1

In [32]:
count/len(true_key["key"].unique())

0.8822674418604651