In [3]:
import pandas as pd
import numpy as np

In [11]:
data = pd.read_excel("../Data/한국마사회_경주상세정보(제주_부경)_20230720.xlsx")

In [17]:
pd.set_option('display.max_columns', None)
data

,MEET,RC_DATE,RC_NO,RC_DIST,RANK,WEATHER,TRACK,ORD,CHUL_NO,HR_NAME,HR_NO,NAME,PRD_NAME,AGE,SEX,RC_TIME,ORD1_CNT_T,ORD2_CNT_T,RC_CNT_T,ORD1_CNT_Y,ORD2_CNT_Y,RC_CNT_Y,WG_HR,WG_BUDAM,JK_NAME,JK_NO,JK_AGE,JK_CAREER,JK_ORD1_CNT_T,JK_ORD2_CNT_T,JK_RC_CNT_T,JK_ORD1_CNT_Y,JK_ORD2_CNT_Y,JK_RC_CNT_Y,TR_NAME,TR_NO,TR_AGE,TR_CAREER,TR_ORD1_CNT_T,TR_ORD2_CNT_T,TR_RC_CNT_T,TR_ORD1_CNT_Y,TR_ORD2_CNT_Y,TR_RC_CNT_Y,HR_ORD1_CNT_T,HR_ORD2_CNT_T,HR_RC_CNT_T,SJ_S1F_ORD,SJ_1C_ORD,SJ_2C_ORD,SJ_3C_ORD,SJ_G3F_ORD,SJ_4C_ORD,SJ_G1F_ORD,SE_S1F_ACC_TIME,SE_1C_ACC_TIME,SE_2C_ACC_TIME,SE_3C_ACC_TIME,SE_G3F_ACC_TIME,SE_4C_ACC_TIME,SE_G1F_ACC_TIME,JE_S1F_TIME,JE_1C_TIME,JE_2C_TIME,JE_3C_TIME,JE_G3F_TIME,JE_4C_TIME,JE_G1F_TIME,BU_S1F_ORD,BU_G8F_ORD,BU_G6F_ORD,BU_G4F_ORD,BU_G3F_ORD,BU_G2F_ORD,BU_G1F_ORD,BU_S1F_TIME,BU_10-8F_TIME,BU_8-6F_TIME,BU_6-4F_TIME,BU_4-2F_TIME,BU_2F-G_TIME,BU_3F-G_TIME,BU_1F-G_TIME,BU_S1F_ACC_TIME,BU_G8F_ACC_TIME,BU_G6F_ACC_TIME,BU_G4F_ACC_TIME,BU_G3F_ACC_TIME,BU_G2F_ACC_TIME,BU_G1F_ACC_TIME
0,경마장,경주일자,경주번호,경주거리,경주등급,날씨,주로상태(함수율),착순,출주번호,마명,마번,출신국가,국산외산구분,마필연령,마필성별,경주기록(초),경주마통산1착횟수,경주마통산2착횟수,경주마통산출전횟수,경주마최근1년1착횟수,경주마최근1년2착횟수,경주마최근1년출전횟수,마체중및증감,부담중량,기수명,기수번호,기수연령,기수경력(년),기수통산1착횟수,기수통산2착횟수,기수통산출전횟수,기수최근1년간1착횟수,기수최근1년간2착횟수,기수최근1년간출전횟수,조교사명,조교사번호,조교사연령(비공개),조교사경력(년),조교사통산1착횟수,조교사통산2착횟수,조교사통산출전횟수,조교사최근1년간1착횟수,조교사최근1년간2착횟수,조교사최근1년간출전횟수,조교사위탁경주마1위횟수,조교사위탁경주마2위횟수,조교사위탁경주마출전횟수,"서울,제주S1F구간통과순위(서울,제주공통)","서울,제주1코너구간통과순위(서울,제주공통)","서울,제주2코너구간통과순위(서울,제주공통)","서울,제주3코너구간통과순위(서울,제주공통)","서울,제주G3F구간통과순위(서울,제주공통)","서울,제주4코너구간통과순위(서울,제주공통)","서울,제주G1F구간통과순위(서울,제주공통)",서울S1F통과누적기록,서울1코너통과누적기록,서울2코너통과누적기록,서울3코너통과누적기록,서울3코너통과누적기록,서울4코너통과누적기록,서울G1F통과누적기록,제주S-1F통과기록,제주1코너통과기록,제주2코너통과기록,제주3코너통과기록,제주G-3F통과기록,제주4코너통과기록,제주G-1F통과기록,부경S1F통과순위,부경G8F통과순위,부경G6F통과순위,부경G4F통과순위,부경G3F통과순위,부경G2F통과순위,부경G1F통과순위,부경S1F통과기록,부경10-8F통과기록,부경8-6F통과기록,부경6-4F통과기록,부경4-2F통과기록,부경2F-G통과기록,부경3F-G통과기록,부경1F-G통과기록,부경S1F통과누적기록,부경G8F통과누적기록,부경G6F통과누적기록,부경G4F통과누적기록,부경G3F통과누적기록,부경G2F통과누적기록,부경G1F통과누적기록
1,제주,20230701,1,800,제6등급,흐림,포화 (18%),1,9,한백제왕,3101848,한국,국산,3,거,65.2,1,0,2,1,0,2,311(-18),55,김준호,003081,30,9,411,337,3025,64,50,413,김영래,002019,NaN,27,1547,1235,10161,48,32,321,90,46,366,2,0,0,2,0,2,1,0,0,0,0,0,0,0,16.8,0,0,16.8,48.4,31.2,18.4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,제주,20230701,1,800,제6등급,흐림,포화 (18%),2,2,명의로운,3102087,한국,국산,3,암,67.3,0,1,5,0,1,5,283(-6),54,원유일,003075,36,13,444,469,4730,26,30,402,변용호,002013,NaN,29,1211,1313,12538,15,24,343,31,81,633,1,0,0,1,0,1,2,0,0,0,0,0,0,0,16.6,0,0,16.6,50.7,31.2,19.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,제주,20230701,1,800,제6등급,흐림,포화 (18%),3,3,번개의꿈,3101489,한국,국산,4,수,67.5,0,0,5,0,0,5,271(-5),55,전현준,003070,35,18,959,810,6130,69,54,434,윤덕상,002021,NaN,27,1036,1279,12632,24,49,493,79,76,724,7,0,0,7,0,6,4,0,0,0,0,0,0,0,17.8,0,0,17.8,49.7,33,17.6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,제주,20230701,1,800,제6등급,흐림,포화 (18%),4,6,고차원,3103528,한국,국산,2,암,67.6,0,0,3,0,0,3,265(-8),54,이성민,003092,29,6,126,142,1573,28,36,389,윤덕상,002021,NaN,27,1036,1279,12632,24,49,493,79,76,724,6,0,0,6,0,7,5,0,0,0,0,0,0,0,17.6,0,0,17.6,50,33.2,17.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29588,제주,20190111,9,900,한4등급,흐림,양호 (8%),6,8,백년친구,1017787,한국,국산,3,암,64.1,2,3,15,0,0,0,308(+5),54.5,권진영,003078,36,10,154,175,1960,0,0,0,박병진,002028,NaN,19,927,936,7980,39,35,381,184,192,1561,2,0,0,2,0,2,3,0,0,0,0,0,0,0,14.7,0,0,21.4,42.7,34.9,15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29589,제주,20190111,9,900,한4등급,흐림,양호 (8%),7,3,미래제주,1017443,한국,국산,4,암,64.2,0,0,8,0,0,0,311(-2),57,전현준,003070,35,18,959,810,6130,69,54,434,이준호,002029,NaN,17,666,702,6512,54,48,432,101,144,1151,4,0,0,4,0,4,4,0,0,0,0,0,0,0,15.2,0,0,21.9,42.3,35.2,14.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29590,제주,20190111,9,900,한4등급,흐림,양호 (8%),8,1,남단여제,1017686,한국,국산,3,암,64.5,2,2,19,0,0,0,282(-4),53,김이랑,003038,48,26,556,678,6435,0,0,0,신경호,002018,NaN,27,1021,1102,10781,41,50,350,112,104,1174,8,0,0,6,0,6,10,0,0,0,0,0,0,0,15.6,0,0,22.3,42.2,35.6,14.8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29591,제주,20190111,9,900,한4등급,흐림,양호 (8%),9,4,섬문화,1017765,한국,국산,4,암,64.6,0,2,26,0,0,0,316(+4),54,문성호,003029,51,31,1141,1206,10297,22,18,233,좌윤철,002009,NaN,32,1078,1277,13727,33,27,360,74,98,1027,9,0,0,9,0,8,9,0,0,0,0,0,0,0,15.7,0,0,22.5,42.1,35.9,14.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29592,제주,20190111,9,900,한4등급,흐림,양호 (8%),10,6,불멸의힘,1017631,한국,국산,3,암,65.1,0,1,18,0,0,0,318(-7),54.5,권동석,003062,42,15,312,326,3141,0,0,0,김성오,002024,NaN,26,804,930,9818,18,27,326,48,61,703,1,0,0,1,0,1,5,0,0,0,0,0,0,0,14.7,0,0,21.3,43.8,34.9,15.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

### 1. 결측치 처리

먼저 결측치가 있는지 확인해보자.

In [18]:
for col in data.columns:
    if data[col].isnull().sum()!=0:
        print(col,':',data[col].isnull().sum())

TR_AGE : 29592
TR_ORD1_CNT_T : 4
TR_ORD2_CNT_T : 4
TR_RC_CNT_T : 4
TR_ORD1_CNT_Y : 4
TR_ORD2_CNT_Y : 4
TR_RC_CNT_Y : 4

7개의 칼럼에서 결측치가 확인되었다. TR_AGE를 제외하고는 다른 모든 칼럼에서 결측치의 개수가 같다. 또 이 칼럼들은 모두 조교사에 관련된 칼럼이다. 조금 더 살펴보자.

In [14]:
data[data["TR_NAME"]=="외부마"]

,MEET,RC_DATE,RC_NO,RC_DIST,RANK,WEATHER,TRACK,ORD,CHUL_NO,HR_NAME,HR_NO,NAME,PRD_NAME,AGE,SEX,RC_TIME,ORD1_CNT_T,ORD2_CNT_T,RC_CNT_T,ORD1_CNT_Y,ORD2_CNT_Y,RC_CNT_Y,WG_HR,WG_BUDAM,JK_NAME,JK_NO,JK_AGE,JK_CAREER,JK_ORD1_CNT_T,JK_ORD2_CNT_T,JK_RC_CNT_T,JK_ORD1_CNT_Y,JK_ORD2_CNT_Y,JK_RC_CNT_Y,TR_NAME,TR_NO,TR_AGE,TR_CAREER,TR_ORD1_CNT_T,TR_ORD2_CNT_T,TR_RC_CNT_T,TR_ORD1_CNT_Y,TR_ORD2_CNT_Y,TR_RC_CNT_Y,HR_ORD1_CNT_T,HR_ORD2_CNT_T,HR_RC_CNT_T,SJ_S1F_ORD,SJ_1C_ORD,SJ_2C_ORD,SJ_3C_ORD,SJ_G3F_ORD,SJ_4C_ORD,SJ_G1F_ORD,SE_S1F_ACC_TIME,SE_1C_ACC_TIME,SE_2C_ACC_TIME,SE_3C_ACC_TIME,SE_G3F_ACC_TIME,SE_4C_ACC_TIME,SE_G1F_ACC_TIME,JE_S1F_TIME,JE_1C_TIME,JE_2C_TIME,JE_3C_TIME,JE_G3F_TIME,JE_4C_TIME,JE_G1F_TIME,BU_S1F_ORD,BU_G8F_ORD,BU_G6F_ORD,BU_G4F_ORD,BU_G3F_ORD,BU_G2F_ORD,BU_G1F_ORD,BU_S1F_TIME,BU_10-8F_TIME,BU_8-6F_TIME,BU_6-4F_TIME,BU_4-2F_TIME,BU_2F-G_TIME,BU_3F-G_TIME,BU_1F-G_TIME,BU_S1F_ACC_TIME,BU_G8F_ACC_TIME,BU_G6F_ACC_TIME,BU_G4F_ACC_TIME,BU_G3F_ACC_TIME,BU_G2F_ACC_TIME,BU_G1F_ACC_TIME
836,제주,20230527,6,1000,제3등급,맑음,건조 (5%),95,8,광명성호,3016266,한국,국산,9,수,0,10,4,68,0,0,3,0(),53,양민재,003096,28,3,12,14,148,11,13,140,외부마,0BBBBB,NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,1305,1208,10930,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5083,제주,20221021,2,800,제6등급,맑음,건조 (4%),95,3,중문보스,3102843,한국,국산,3,거,0,0,0,5,0,0,5,0(),54,이동준,003086,30,7,27,30,503,3,8,94,외부마,0BBBBB,NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,1308,1173,10954,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9559,제주,20220311,5,900,제5등급,맑음,건조 (4%),94,5,검은맹주,3102504,한국,국산,3,수,0,3,0,14,1,0,6,0(),55.5,정명일,003044,48,27,704,668,6670,18,20,274,외부마,0BBBBB,NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,1044,952,9013,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9935,제주,20220219,6,1400,한2등급,흐림,포화 (17%),95,4,완벽한,1017428,한국,국산,7,암,0,3,6,44,0,0,4,0(),63,김용섭,003006,55,33,1327,1057,8767,3,15,116,외부마,0BBBBB,NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,1031,940,8732,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

TR_NAME이 외부마로 지정되어 있을 경우 조교사에 관련된 6개의 칼럼이 NaN으로지정되는 것을 확인할 수 있다.

### 2. 단일 값으로 이루어진 칼럼 처리

모든 행에 대해서 단일 값으로 이루어진 열들이 많이 보인다. 이들은 정보가 없다고 봐도 무방함으로 drop한다.

In [15]:
unicol_list = []
for col in data.columns:
    if data[1:][col].nunique()<=1:
        unicol_list.append(col)

In [16]:
drop_data = data.drop(unicol_list,axis=1) 
drop_data

,RC_DATE,RC_NO,RC_DIST,RANK,WEATHER,TRACK,ORD,CHUL_NO,HR_NAME,HR_NO,AGE,SEX,RC_TIME,ORD1_CNT_T,ORD2_CNT_T,RC_CNT_T,ORD1_CNT_Y,ORD2_CNT_Y,RC_CNT_Y,WG_HR,WG_BUDAM,JK_NAME,JK_NO,JK_AGE,JK_CAREER,JK_ORD1_CNT_T,JK_ORD2_CNT_T,JK_RC_CNT_T,JK_ORD1_CNT_Y,JK_ORD2_CNT_Y,JK_RC_CNT_Y,TR_NAME,TR_NO,TR_CAREER,TR_ORD1_CNT_T,TR_ORD2_CNT_T,TR_RC_CNT_T,TR_ORD1_CNT_Y,TR_ORD2_CNT_Y,TR_RC_CNT_Y,HR_ORD1_CNT_T,HR_ORD2_CNT_T,HR_RC_CNT_T,SJ_S1F_ORD,SJ_1C_ORD,SJ_2C_ORD,SJ_3C_ORD,SJ_4C_ORD,SJ_G1F_ORD,JE_S1F_TIME,JE_1C_TIME,JE_2C_TIME,JE_3C_TIME,JE_G3F_TIME,JE_4C_TIME,JE_G1F_TIME
0,경주일자,경주번호,경주거리,경주등급,날씨,주로상태(함수율),착순,출주번호,마명,마번,마필연령,마필성별,경주기록(초),경주마통산1착횟수,경주마통산2착횟수,경주마통산출전횟수,경주마최근1년1착횟수,경주마최근1년2착횟수,경주마최근1년출전횟수,마체중및증감,부담중량,기수명,기수번호,기수연령,기수경력(년),기수통산1착횟수,기수통산2착횟수,기수통산출전횟수,기수최근1년간1착횟수,기수최근1년간2착횟수,기수최근1년간출전횟수,조교사명,조교사번호,조교사경력(년),조교사통산1착횟수,조교사통산2착횟수,조교사통산출전횟수,조교사최근1년간1착횟수,조교사최근1년간2착횟수,조교사최근1년간출전횟수,조교사위탁경주마1위횟수,조교사위탁경주마2위횟수,조교사위탁경주마출전횟수,"서울,제주S1F구간통과순위(서울,제주공통)","서울,제주1코너구간통과순위(서울,제주공통)","서울,제주2코너구간통과순위(서울,제주공통)","서울,제주3코너구간통과순위(서울,제주공통)","서울,제주4코너구간통과순위(서울,제주공통)","서울,제주G1F구간통과순위(서울,제주공통)",제주S-1F통과기록,제주1코너통과기록,제주2코너통과기록,제주3코너통과기록,제주G-3F통과기록,제주4코너통과기록,제주G-1F통과기록
1,20230701,1,800,제6등급,흐림,포화 (18%),1,9,한백제왕,3101848,3,거,65.2,1,0,2,1,0,2,311(-18),55,김준호,003081,30,9,411,337,3025,64,50,413,김영래,002019,27,1547,1235,10161,48,32,321,90,46,366,2,0,0,2,2,1,16.8,0,0,16.8,48.4,31.2,18.4
2,20230701,1,800,제6등급,흐림,포화 (18%),2,2,명의로운,3102087,3,암,67.3,0,1,5,0,1,5,283(-6),54,원유일,003075,36,13,444,469,4730,26,30,402,변용호,002013,29,1211,1313,12538,15,24,343,31,81,633,1,0,0,1,1,2,16.6,0,0,16.6,50.7,31.2,19.5
3,20230701,1,800,제6등급,흐림,포화 (18%),3,3,번개의꿈,3101489,4,수,67.5,0,0,5,0,0,5,271(-5),55,전현준,003070,35,18,959,810,6130,69,54,434,윤덕상,002021,27,1036,1279,12632,24,49,493,79,76,724,7,0,0,7,6,4,17.8,0,0,17.8,49.7,33,17.6
4,20230701,1,800,제6등급,흐림,포화 (18%),4,6,고차원,3103528,2,암,67.6,0,0,3,0,0,3,265(-8),54,이성민,003092,29,6,126,142,1573,28,36,389,윤덕상,002021,27,1036,1279,12632,24,49,493,79,76,724,6,0,0,6,7,5,17.6,0,0,17.6,50,33.2,17.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29588,20190111,9,900,한4등급,흐림,양호 (8%),6,8,백년친구,1017787,3,암,64.1,2,3,15,0,0,0,308(+5),54.5,권진영,003078,36,10,154,175,1960,0,0,0,박병진,002028,19,927,936,7980,39,35,381,184,192,1561,2,0,0,2,2,3,14.7,0,0,21.4,42.7,34.9,15
29589,20190111,9,900,한4등급,흐림,양호 (8%),7,3,미래제주,1017443,4,암,64.2,0,0,8,0,0,0,311(-2),57,전현준,003070,35,18,959,810,6130,69,54,434,이준호,002029,17,666,702,6512,54,48,432,101,144,1151,4,0,0,4,4,4,15.2,0,0,21.9,42.3,35.2,14.9
29590,20190111,9,900,한4등급,흐림,양호 (8%),8,1,남단여제,1017686,3,암,64.5,2,2,19,0,0,0,282(-4),53,김이랑,003038,48,26,556,678,6435,0,0,0,신경호,002018,27,1021,1102,10781,41,50,350,112,104,1174,8,0,0,6,6,10,15.6,0,0,22.3,42.2,35.6,14.8
29591,20190111,9,900,한4등급,흐림,양호 (8%),9,4,섬문화,1017765,4,암,64.6,0,2,26,0,0,0,316(+4),54,문성호,003029,51,31,1141,1206,10297,22,18,233,좌윤철,002009,32,1078,1277,13727,33,27,360,74,98,1027,9,0,0,9,8,9,15.7,0,0,22.5,42.1,35.9,14.9
29592,20190111,9,900,한4등급,흐림,양호 (8%),10,6,불멸의힘,1017631,3,암,65.1,0,1,18,0,0,0,318(-7),54.5,권동석,003062,42,15,312,326,3141,0,0,0,김성오,002024,26,804,930,9818,18,27,326,48,61,703,1,0,0,1,1,5,14.7,0,0,21.3,43.8,34.9,15.7

### 3. 기타 칼럼 수정

In [114]:
drop_data["WG"] = drop_data["WG_HR"].str.extract(r'(\d+)(?=\()')
drop_data["WG"][0]="마체중"

drop_data["WC"] = drop_data["WG_HR"].str.extract(r'\((.*?)\)')
drop_data["WC"][0] = "체중증감"

drop_data["WC"][1:] = pd.to_numeric(drop_data["WC"][1:])
drop_data["WG"][1:] = pd.to_numeric(drop_data["WG"][1:])

drop_data = drop_data.drop(["WG_HR"],axis=1)

In [9]:
drop_data

NameError: name 'drop_data' is not defined

In [8]:
pd.set_option('display.max_columns', None)
pd.read_csv("../Data/weather2022.csv",encoding="cp949")

,지점,지점명,일시,기온(°C),기온 QC플래그,강수량(mm),강수량 QC플래그,풍속(m/s),풍속 QC플래그,풍향(16방위),풍향 QC플래그,습도(%),습도 QC플래그,증기압(hPa),이슬점온도(°C),현지기압(hPa),현지기압 QC플래그,해면기압(hPa),해면기압 QC플래그,일조(hr),일조 QC플래그,일사(MJ/m2),일사 QC플래그,적설(cm),3시간신적설(cm),전운량(10분위),중하층운량(10분위),운형(운형약어),최저운고(100m ),시정(10m),지면상태(지면상태코드),현상번호(국내식),지면온도(°C),지면온도 QC플래그,5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,184,제주,2022.1.1 1:00,3.3,NaN,NaN,NaN,2.4,NaN,360.0,NaN,66.0,NaN,5.1,-2.4,1030.1,NaN,1032.7,NaN,NaN,9.0,NaN,9.0,NaN,NaN,6.0,6.0,NaN,3.0,5000.0,NaN,NaN,3.1,NaN,6.6,7.0,7.9,8.9
1,184,제주,2022.1.1 2:00,3.2,NaN,NaN,NaN,3.1,NaN,20.0,NaN,59.0,NaN,4.5,-4.0,1029.7,NaN,1032.3,NaN,NaN,9.0,NaN,9.0,NaN,NaN,8.0,6.0,NaN,16.0,5000.0,NaN,NaN,2.8,NaN,6.5,6.9,7.9,8.8
2,184,제주,2022.1.1 3:00,3.0,NaN,NaN,NaN,4.1,NaN,50.0,NaN,62.0,NaN,4.7,-3.5,1029.4,NaN,1032.0,NaN,NaN,9.0,NaN,9.0,NaN,NaN,2.0,1.0,ScAc,9.0,5000.0,NaN,NaN,2.4,NaN,6.3,6.8,7.8,8.8
3,184,제주,2022.1.1 4:00,2.5,NaN,NaN,NaN,3.6,NaN,20.0,NaN,61.0,NaN,4.5,-4.2,1029.4,NaN,1032.0,NaN,NaN,9.0,NaN,9.0,NaN,NaN,1.0,1.0,Sc,8.0,5000.0,NaN,NaN,1.9,NaN,6.2,6.7,7.7,8.8
4,184,제주,2022.1.1 5:00,2.2,NaN,NaN,NaN,2.6,NaN,20.0,NaN,67.0,NaN,4.8,-3.3,1029.0,NaN,1031.6,NaN,NaN,9.0,NaN,9.0,NaN,NaN,1.0,1.0,Sc,8.0,5000.0,NaN,NaN,1.4,NaN,6.1,6.6,7.7,8.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34939,189,서귀포,2022.12.30 20:00,5.3,NaN,NaN,NaN,0.8,NaN,340.0,NaN,66.0,NaN,5.9,-0.5,1025.1,NaN,1031.6,NaN,NaN,9.0,NaN,9.0,NaN,NaN,9.0,7.0,NaN,40.0,1441.0,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN
34940,189,서귀포,2022.12.30 21:00,5.3,NaN,NaN,NaN,1.0,NaN,360.0,NaN,67.0,NaN,6.0,-0.3,1025.2,NaN,1031.7,NaN,NaN,9.0,NaN,9.0,NaN,NaN,9.0,9.0,Ac,40.0,1671.0,NaN,NaN,5.7,NaN,NaN,NaN,NaN,NaN
34941,189,서귀포,2022.12.30 22:00,5.1,NaN,NaN,NaN,0.2,NaN,0.0,NaN,68.0,NaN,6.0,-0.3,1025.3,NaN,1031.8,NaN,NaN,9.0,NaN,9.0,NaN,NaN,6.0,6.0,NaN,12.0,1588.0,NaN,NaN,5.5,NaN,NaN,NaN,NaN,NaN
34942,189,서귀포,2022.12.30 23:00,5.3,NaN,NaN,NaN,0.6,NaN,360.0,NaN,63.0,NaN,5.6,-1.1,1025.2,NaN,1031.7,NaN,NaN,9.0,NaN,9.0,NaN,NaN,8.0,5.0,NaN,12.0,1563.0,NaN,NaN,5.2,NaN,NaN,NaN,NaN,NaN
34943,189,서귀포,2022.12.31 0:00,4.4,NaN,NaN,NaN,0.5,NaN,360.0,NaN,69.0,NaN,5.8,-0.8,1025.0,NaN,1031.5,NaN,NaN,9.0,NaN,9.0,NaN,NaN,2.0,2.0,NaN,NaN,1727.0,NaN,NaN,4.6,NaN,NaN,NaN,NaN,NaN

In [9]:
data1 = pd.read_excel("/Users/ichang-ug/Downloads/경마데이터.xls")

In [12]:
null_count = data1.isnull().sum()
null_count

경주일자              0
경주번호              0
경주거리              0
날씨                0
착순                0
               ...
조교사위탁경주마2위승률      0
주로상태            200
주로상태_함수율          0
혈통                0
등급                0
Length: 73, dtype: int64

In [13]:
type(null_count)

pandas.core.series.Series

In [14]:
not_null = len(data1)-null_count

In [16]:
not_null.to_excel("../../../../Downloads/not_null.xlsx")