In [1]:
import pandas as pd
import numpy as np

In [39]:
weather19 = pd.read_csv("../Data/weather2019.csv", encoding='cp949')
weather20 = pd.read_csv("../Data/weather2020.csv", encoding='cp949')
weather21 = pd.read_csv("../Data/weather2021.csv", encoding='cp949')
weather22 = pd.read_csv("../Data/weather2022.csv", encoding='cp949')
weather23 = pd.read_csv("../Data/weather2023.csv", encoding='cp949')

In [40]:
weather = pd.concat([weather19,weather20,weather21,weather22,weather23],axis=0)

In [43]:
weather = weather[weather["지점"]==184]

In [44]:
weather

,지점,지점명,일시,기온(°C),기온 QC플래그,강수량(mm),강수량 QC플래그,풍속(m/s),풍속 QC플래그,풍향(16방위),...,최저운고(100m ),시정(10m),지면상태(지면상태코드),현상번호(국내식),지면온도(°C),지면온도 QC플래그,5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,184,제주,2019.1.1 1:00,5.2,0.0,NaN,NaN,3.8,NaN,290.0,...,8.0,2000.0,NaN,NaN,4.4,0.0,6.3,6.1,5.8,9.2
1,184,제주,2019.1.1 2:00,5.7,0.0,NaN,NaN,4.2,NaN,320.0,...,9.0,2000.0,NaN,NaN,4.4,0.0,6.3,6.0,5.8,9.3
2,184,제주,2019.1.1 3:00,5.8,0.0,NaN,NaN,4.6,NaN,290.0,...,9.0,2000.0,NaN,NaN,4.5,0.0,6.3,6.1,5.8,9.3
3,184,제주,2019.1.1 4:00,6.1,0.0,NaN,NaN,4.6,NaN,290.0,...,9.0,2000.0,NaN,NaN,4.7,0.0,6.3,6.0,5.8,9.2
4,184,제주,2019.1.1 5:00,5.8,0.0,NaN,NaN,4.7,NaN,290.0,...,9.0,2000.0,NaN,NaN,4.6,0.0,6.3,6.0,5.8,9.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4315,184,제주,2023.6.29 20:00,28.9,NaN,NaN,NaN,5.5,NaN,230.0,...,NaN,5000.0,NaN,NaN,28.4,NaN,29.3,29.1,28.8,26.7
4316,184,제주,2023.6.29 21:00,28.8,NaN,NaN,NaN,6.1,NaN,250.0,...,10.0,5000.0,NaN,NaN,27.6,NaN,29.2,28.9,28.8,26.7
4317,184,제주,2023.6.29 22:00,28.5,NaN,NaN,NaN,5.8,NaN,230.0,...,22.0,5000.0,NaN,NaN,27.1,NaN,29.0,28.8,28.7,26.8
4318,184,제주,2023.6.29 23:00,28.4,NaN,NaN,NaN,6.6,NaN,250.0,...,2.0,5000.0,NaN,NaN,26.8,NaN,28.9,28.6,28.6,26.8
4319,184,제주,2023.6.30 0:00,25.2,NaN,0.9,NaN,3.9,NaN,270.0,...,6.0,4413.0,NaN,1.0,25.0,NaN,28.7,28.4,28.5,26.9